// @ts-nocheck
import { useRef, useEffect, useCallback, useState } from "react";
import { animate } from "animejs";
var S = 126, CL = S / 7, MX = 6;
var RI = [
  {rx:90,ry:36,sp:.35,c:"oklch(0.72 0.2 85 / 0.7)",n:12,sz:2.5,ri:"oklch(0.72 0.2 85 / 0.12)"},
  {rx:80,ry:30,sp:-.3,c:"oklch(0.63 0.15 20 / 0.55)",n:8,sz:2,ri:"oklch(0.63 0.15 20 / 0.08)"},
  {rx:96,ry:28,sp:.5,c:"rgba(255,255,255,0.4)",n:6,sz:2,ri:"rgba(255,255,255,0.06)"},
  {rx:84,ry:40,sp:-.45,c:"oklch(0.68 0.18 50 / 0.5)",n:8,sz:2.5,ri:"oklch(0.68 0.18 50 / 0.1)"},
];
function se(c,n,m){m=m||1;for(var i=0;i<n;i++){var e=document.createElement("div");var s=(2+Math.random()*3)*m,a=Math.random()*Math.PI*2,d=(5+Math.random()*20)*m;e.style.cssText="position:absolute;left:63px;top:63px;border-radius:50%;width:"+s+"px;height:"+s+"px;pointer-events:none;background:oklch("+(.6+Math.random()*.2)+" .25 "+(20+Math.random()*30)+");box-shadow:0 0 "+(s*3)+"px "+s+"px oklch(.7 .25 35/.5);";c.appendChild(e);animate(e,{translateX:Math.cos(a)*d,translateY:Math.sin(a)*d-10,opacity:[1,0],scale:[1,0.2],duration:400+Math.random()*400,ease:"out(2)",onComplete:function(){e.remove()}});}}
function sw(c){for(var i=0;i<2;i++){var r=document.createElement("div");r.style.cssText="position:absolute;left:50%;top:50%;border-radius:50%;width:0;height:0;pointer-events:none;border:"+(2-i)+"px solid oklch("+(.85-i*.15)+" .3 "+(35+i*10)+"/"+(.8-i*.3)+");transform:translate(-50%,-50%);";c.appendChild(r);animate(r,{width:[0,160+i*50],height:[0,160+i*50],opacity:[.9,0],duration:600+i*200,delay:i*80,ease:"out(3)",onComplete:function(){r.remove()}});}}
export default function AvatarWithJelly(){var d=0,p="idle",br,fr,ar;var st=useState(0);d=st[0];var setD=st[1];var st2=useState("idle");p=st2[0];var setP=st2[1];br=useRef(null);fr=useRef(null);ar=useRef(null);var h=useCallback(function(){if(p!=="idle")return;var n=d+1;setD(n);var c=ar.current;if(!c)return;var it=3+n*2;animate(c,{translateX:[0,(Math.random()-.5)*it,(Math.random()-.5)*it*.6,0],translateY:[0,(Math.random()-.5)*it,(Math.random()-.5)*it*.6,0],duration:300+n*20,ease:"out(3)"});se(c,2+n,1);if(n>=MX){setP("bang");var ff=document.createElement("div");ff.style.cssText="position:fixed;inset:0;z-index:9999;background:white;pointer-events:none;";document.body.appendChild(ff);animate(ff,{opacity:[0,1,.7,0],duration:800,ease:"out(3)",onComplete:function(){ff.remove()}});var hh=document.documentElement;hh.style.transition="transform .6s ease-out";hh.style.transform="translate("+((Math.random()-.5)*12)+"px,"+((Math.random()-.5)*12)+"px)";setTimeout(function(){hh.style.transform="translate("+((Math.random()-.5)*8)+"px,"+((Math.random()-.5)*8)+"px)";setTimeout(function(){hh.style.transform="";hh.style.transition="";},200);},100);if(fr.current)sw(fr.current);var img=c.querySelector("img");if(img)img.style.display="none";var fl=[];for(var R=0;R<7;R++)for(var Col=0;Col<7;Col++){var x=Col*CL,y=R*CL;if(![[x,y],[x+CL,y],[x,y+CL],[x+CL,y+CL]].some(function(a){return Math.hypot(a[0]-63,a[1]-63)<=63}))continue;var dd=document.createElement("div");var j=CL*.25;dd.style.cssText="position:absolute;left:"+x+"px;top:"+y+"px;width:"+(CL+1)+"px;height:"+(CL+1)+"px;clip-path:polygon("+((Math.random()-.5)*j)+"px "+((Math.random()-.5)*j)+"px,"+(CL+(Math.random()-.5)*j)+"px "+((Math.random()-.5)*j)+"px,"+(CL+(Math.random()-.5)*j)+"px "+(CL+(Math.random()-.5)*j)+"px,"+((Math.random()-.5)*j)+"px "+(CL+(Math.random()-.5)*j)+"px);background-image:url("+import.meta.env.BASE_URL+"avatar.png);background-size:"+S+"px "+S+"px;background-position:"+(-x)+"px "+(-y)+"px;";c.appendChild(dd);fl.push(dd);var aa=Math.random()*Math.PI*2;animate(dd,{translateX:Math.cos(aa)*(40+Math.random()*180),translateY:Math.sin(aa)*(40+Math.random()*180),rotate:(Math.random()-.5)*800,opacity:[1,0.3],duration:500+Math.random()*600,ease:"out(3)",delay:Math.random()*60});}for(var i=0;i<5;i++)setTimeout(function(){se(c,8,1.2);},100+i*60);setTimeout(function(){setP("fix");fl.forEach(function(dd){animate(dd,{translateX:0,translateY:0,rotate:0,opacity:1,duration:600+Math.random()*300,ease:"outBack(1.7)",delay:Math.random()*100,onComplete:function(){dd.remove()}});});setTimeout(function(){if(img)img.style.display="";setD(0);setP("idle");},1000);},1800);}},[d,p]);
useEffect(function(){var bk=br.current,f=fr.current;if(!bk||!f)return;var rs=[];RI.forEach(function(c){var r=document.createElement("div");r.style.cssText="position:absolute;border-radius:50%;pointer-events:none;width:"+(c.rx*2)+"px;height:"+(c.ry*2)+"px;left:50%;top:50%;margin-left:-"+c.rx+"px;margin-top:-"+c.ry+"px;border:1px solid "+c.ri+";";bk.appendChild(r);rs.push(r);});var all=[];RI.forEach(function(c){for(var i=0;i<c.n;i++){var d2=document.createElement("div");var s=c.sz;d2.style.cssText="position:absolute;border-radius:50%;pointer-events:none;width:"+s+"px;height:"+s+"px;background:"+c.c+";box-shadow:0 0 "+(s*4)+"px "+(s*1.5)+"px "+c.c+";left:50%;top:50%;transition:opacity .25s;";bk.appendChild(d2);all.push({el:d2,rx:c.rx,ry:c.ry,sp:c.sp,o:(i/c.n)*Math.PI*2,f:false});}});var drv={a:0};var an=animate(drv,{a:Math.PI*2,duration:35000,ease:"linear",loop:true,onUpdate:function(){var a=drv.a;all.forEach(function(d){var ang=a*d.sp+d.o,ca=Math.cos(ang);d.el.style.translate=ca*d.rx+"px "+Math.sin(ang)*d.ry+"px";var tf=ca>.05;if(tf&&d.el.parentElement===bk&&!d.f){d.f=true;d.el.style.opacity="0";setTimeout(function(){f.appendChild(d.el);d.el.style.opacity="";d.f=false;},250);}else if(!tf&&d.el.parentElement===f&&!d.f){d.f=true;d.el.style.opacity="0";setTimeout(function(){bk.appendChild(d.el);d.el.style.opacity="";d.f=false;},250);}});}});return function(){an.pause();all.forEach(function(d){d.el.remove();});rs.forEach(function(r){r.remove();});};},[]);
var gi=d/MX;var bs=p==="idle"?(d===0?"0 0 25px 4px oklch(0.7 0.2 85/0.2),0 0 60px 10px oklch(0.7 0.2 85/0.08)":"0 0 "+(25+gi*40)+"px "+(4+gi*12)+"px oklch(0.7 "+(.2+gi*.25)+" "+(85-gi*50)+"/"+(.2+gi*.5)+"),0 0 "+(60+gi*60)+"px "+(10+gi*20)+"px oklch(0.7 "+(.2+gi*.15)+" "+(85-gi*40)+"/"+(.08+gi*.35)+")"):"0 0 50px 15px oklch(0.85 0.35 35/0.8),0 0 120px 35px oklch(0.85 0.35 35/0.4)";
return React.createElement("div",{className:"relative mx-auto mb-10 flex items-center justify-center",style:{width:220,height:220}},React.createElement("div",{ref:br,className:"absolute inset-0 z-0"}),React.createElement("div",{ref:fr,className:"absolute inset-0 z-10 pointer-events-none"}),React.createElement("div",{ref:ar,onClick:h,className:"relative flex items-center justify-center rounded-full cursor-pointer select-none overflow-visible",style:{width:S,height:S,zIndex:1,boxShadow:bs,animation:p==="idle"&&d===0?"breathe-amber 3s ease-in-out infinite":"none"},role:"img","aria-label":"avatar"},React.createElement("img",{src:import.meta.env.BASE_URL+"avatar.png",alt:"",className:"h-full w-full rounded-full object-cover pointer-events-none",draggable:false,style:{clipPath:"circle(50%)",transition:"opacity .3s",opacity:p==="idle"?Math.max(0,1-d*0.18):1}}),d>0&&p==="idle"?React.createElement("div",{className:"absolute inset-0 rounded-full pointer-events-none",style:{zIndex:1,background:"radial-gradient(circle at 50% 50%,oklch("+(0.7+gi*.2)+" 0.3 "+(55-gi*30)+"/"+(0.1+gi*.35)+") 0%,transparent "+(55-gi*18)+"%)",mixBlendMode:"screen"}}):null));}
